server.port=8080
server.address=app.johannes-reis.dev
server.ssl.enabled=true
server.ssl.certificate=file:/opt/graphql_server/ssl/johannes-reis.dev.cer
server.ssl.certificate-private-key=file:/opt/graphql_server/ssl/johannes-reis.dev.key