package com.example.graphqlserver.controller;

import java.time.OffsetDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.graphql.data.method.annotation.Argument;
import org.springframework.graphql.data.method.annotation.MutationMapping;
import org.springframework.graphql.data.method.annotation.QueryMapping;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;

import com.example.graphqlserver.model.CalendarEvent;
import com.example.graphqlserver.model.CalendarEvent.CreateCalendarEventInput;
import com.example.graphqlserver.model.CalendarEvent.UpdateCalendarEventInput;
import com.example.graphqlserver.model.UserPrincipal;
import com.example.graphqlserver.repository.CalendarEventRepository;

@Controller
public class CalendarEventController {

    @Autowired
    private CalendarEventRepository calendarEventRepository; // @todo use todoService as abstraction layer

    @QueryMapping
    public List<CalendarEvent> calendarEvents() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        UserPrincipal user = (UserPrincipal) authentication.getPrincipal();
        return this.calendarEventRepository.findCalendarEventByUserId(user.getId());
    }

    @QueryMapping // @todo check if needed, if yes, only return if userId is correct, currently
                  // you can get calenarEvents of other users
    public CalendarEvent calendarEventById(@Argument String id) {
        return calendarEventRepository.findCalendarEventById(id)
                .orElse(null);
    }

    @MutationMapping
    public CalendarEvent createCalendarEvent(@Argument("input") CreateCalendarEventInput input) {

        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        UserPrincipal user = (UserPrincipal) authentication.getPrincipal();
        CalendarEvent newCalendarEvent = new CalendarEvent(
                null, // The ID will be generated by MongoDB
                user.getId(),
                input.title(),
                input.start(),
                input.end(),
                input.color(),
                input.description(),
                input.location(),
                OffsetDateTime.now(),
                OffsetDateTime.now());

        // Save to repository and return the saved entity (with generated ID)
        return calendarEventRepository.save(newCalendarEvent);
    }

    @MutationMapping
    public CalendarEvent updateCalendarEvent(@Argument("input") UpdateCalendarEventInput input) {
        // Create a new Todo with all fields from input but with a generated ID
        return calendarEventRepository.findById(input.id())
                .map(existingcalendarEvent -> {
                    // Create a new Todo with updated fields while preserving unmodified fields
                    CalendarEvent updatedCalendarEvent = new CalendarEvent(
                            existingcalendarEvent.id(),
                            existingcalendarEvent.userId(),
                            input.title() != null ? input.title() : existingcalendarEvent.title(),
                            input.start() != null ? input.start() : existingcalendarEvent.start(),
                            input.end() != null ? input.end() : existingcalendarEvent.end(),
                            input.color() != null ? input.color() : existingcalendarEvent.color(),
                            input.description() != null ? input.description() : existingcalendarEvent.description(),
                            input.location() != null ? input.location() : existingcalendarEvent.location(),
                            existingcalendarEvent.created(),
                            OffsetDateTime.now());

                    // Save and return the updated Todo
                    return calendarEventRepository.save(updatedCalendarEvent);
                })
                .orElse(null);
    }

    @MutationMapping
    public String deleteCalendarEvent(@Argument String id) { // @todo check if id is available, if not return error
        calendarEventRepository.findById(id).orElse(null); // @todo only delete if userId is correct
        calendarEventRepository.deleteById(id);
        return id;

    }
}
