package com.example.graphqlserver.controller;

import java.time.OffsetDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.graphql.data.method.annotation.Argument;
import org.springframework.graphql.data.method.annotation.MutationMapping;
import org.springframework.graphql.data.method.annotation.QueryMapping;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;

import com.example.graphqlserver.model.Todo;
import com.example.graphqlserver.model.Todo.CreateTodoInput;
import com.example.graphqlserver.model.Todo.UpdateTodoInput;
import com.example.graphqlserver.model.UserPrincipal;
import com.example.graphqlserver.repository.TodoRepository;

@Controller
public class TodoController {

    @Autowired
    private TodoRepository todoRepository; // @todo use todoService as abstraction layer

    @QueryMapping
    public List<Todo> todos() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        // String userId = (String) authentication.getPrincipal();
        UserPrincipal user = (UserPrincipal) authentication.getPrincipal();
        // Why is anonymous user?
        return this.todoRepository.findTodoByUserId(user.getId());
    }

    @QueryMapping
    public List<Todo> todosByCompleted(@Argument boolean completed) {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        UserPrincipal user = (UserPrincipal) authentication.getPrincipal();
        return this.todoRepository.findByUserIdAndCompleted(user.getId(), completed);
    }


    @QueryMapping // @todo check if needed, if yes, only return if userId is correct
    public Todo todoById(@Argument String id) {
        return todoRepository.findTodoById(id)
                .orElse(null);
        // .orElseThrow(() -> new RuntimeException("Todo not found with id: " + id));
    }


    @MutationMapping
    public Todo createTodo(@Argument("input") CreateTodoInput input) {
        // Create a new Todo with all fields from input but with a generated ID
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        UserPrincipal user = (UserPrincipal) authentication.getPrincipal();
        Todo newTodo = new Todo(
                null, // The ID will be generated by MongoDB
                user.getId(),
                input.title(),
                input.description(),
                input.completed() != null ? input.completed() : Boolean.FALSE,
                input.priority(),
                input.due(),
                input.color(),
                OffsetDateTime.now(),
                OffsetDateTime.now());

        // Save to repository and return the saved entity (with generated ID)
        return todoRepository.save(newTodo);
    }

    @MutationMapping
    public Todo updateTodo(@Argument("input") UpdateTodoInput input) {
        // Create a new Todo with all fields from input but with a generated ID
        return todoRepository.findById(input.id())
                .map(existingTodo -> {
                    // Create a new Todo with updated fields while preserving unmodified fields
                    Todo updatedTodo = new Todo(
                            existingTodo.id(),
                            existingTodo.userId(),
                            input.title() != null ? input.title() : existingTodo.title(),
                            input.description() != null ? input.description() : existingTodo.description(),
                            input.completed() != null ? input.completed() : existingTodo.completed(),
                            input.priority() != null ? input.priority() : existingTodo.priority(),
                            input.due() != null ? input.due() : existingTodo.due(),
                            input.color() != null ? input.color() : existingTodo.color(),
                            existingTodo.created(),
                            OffsetDateTime.now());

                    // Save and return the updated Todo
                    return todoRepository.save(updatedTodo);
                })
                .orElse(null);
    }

    @MutationMapping
    public String deleteTodo(@Argument String id) { // @todo check if id is available, if not return error
        todoRepository.findById(id).orElse(null); // @todo only delete if userId is correct
        todoRepository.deleteById(id);
        return id;

    }
}
